export const employees = [
  {
    id: 1,
    name: 'Aino Virtanen',
    title: 'HR Manager',
    salary: 4200,
    phone: '040-1234567',
    email: 'aino.virtanen@example.com',
    animal: 'Owl',
    startDate: '2015-09-29',
    location: 'Helsinki',
    department: 'Human Resources',
    skills: ['Recruiting', 'Communication', 'Employee Relations'],
  },

  {
    id: 2,
    name: 'liina Koskinen',
    title: 'Backend Developer',
    salary: 3800,
    phone: '040-1234567',
    email: 'liina.koskinen@gmail.com',
    animal: 'Snake',
    startDate: '2025-06-01',
    location: 'Helsinki',
    department: 'IT',
    skills: ['React', 'Wordpress', 'PHP'],
  },

  {
    id: 3,
    name: 'Sara Korhonen',
    title: 'UI/UX Designer',
    salary: 4500,
    phone: '040-3456789',
    email: 'sara.korhonen@example.com',
    animal: 'Cat',
    startDate: '2020-10-29',
    location: 'Helsinki',
    department: 'Design',
    skills: ['Figma', 'Adobe XD', 'User Research'],
  },

  {
    id: 4,
    name: 'Laura Heikkinen',
    title: 'Financial Analyst',
    salary: 5000,
    phone: '040-5678901',
    email: 'laura.heikkinen@example.com',
    animal: 'Rabbit',
    startDate: '2016-01-12',
    location: 'Turku',
    department: 'Finance',
    skills: ['Excel', 'Forecasting', 'Reporting'],
  },

  {
    id: 5,
    name: 'Juha Mäkelä',
    title: 'Operations Lead',
    salary: 5500,
    phone: '040-8901234',
    email: 'juha.makela@example.com',
    animal: 'Eagle',
    startDate: '2014-09-01',
    location: 'Helsinki',
    department: 'Operations',
    skills: ['Planning', 'Management', 'Optimization'],
  },

  {
    id: 6,
    name: 'Emma Koskinen',
    title: 'Customer Success Manager',
    salary: 4300,
    phone: '040-9012345',
    email: 'emma.koskinen@example.com',
    animal: 'Swan',
    startDate: '2022-01-05',
    location: 'Oulu',
    department: 'Customer Relations',
    skills: ['Communication', 'CRM', 'Empathy'],
  },

  {
    id: 7,
    name: 'Ville Lehtonen',
    title: 'Data Analyst',
    salary: 4700,
    phone: '040-0123456',
    email: 'ville.lehtonen@example.com',
    animal: 'Wolf',
    startDate: '2025-05-22',
    location: 'Helsinki',
    department: 'Data',
    skills: ['SQL', 'Python', 'Data Visualization'],
  },

  {
    id: 8,
    name: 'Maria Rantanen',
    title: 'QA Engineer',
    salary: 4100,
    phone: '040-7890123',
    email: 'maria.rantanen@example.com',
    animal: 'Dolphin',
    startDate: '2021-06-18',
    location: 'Espoo',
    department: 'IT',
    skills: ['Testing', 'Cypress', 'Automation'],
  },

  {
    id: 9,
    name: 'Laura Jarvinen',
    title: 'Project Manager',
    salary: 6200,
    phone: '040-1234567',
    email: 'laura.jarvinen@example.com',
    animal: 'Owl',
    startDate: '2018-04-01',
    location: 'Helsinki',
    department: 'Managment',
    skills: ['Communication', 'Employee Relations', 'Recruiting'],
  },
  {
    id: 10,
    name: 'Oskari Vakka',
    title: 'Marketing lead',
    salary: 5200,
    phone: '040-1234567',
    email: 'oskari.vakka@example.com',
    animal: 'Horse',
    startDate: '2025-08-01',
    location: 'Helsinki',
    department: 'Marketing',
    skills: ['Recruiting', 'Communication', 'Employee Relations'],
  },
];
