name: Test Foundry Connection

on:
  workflow_dispatch:

jobs:
  test-model:
    environment: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install OpenAI SDK
        run: |
          pip install openai

      - name: Check environment variables
        env:
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            FOUNDRY_API_KEY: ${{ secrets.FOUNDRY_API_KEY }}
        run: |
            if [ -n "$OPENAI_API_KEY" ]; then
                echo "OPENAI_API_KEY exists"
            else
                echo "OPENAI_API_KEY missing"
            fi

            if [ -n "$FOUNDRY_API_KEY" ]; then
                echo "FOUNDRY_API_KEY exists"
            else
                echo "FOUNDRY_API_KEY missing"
            fi

      - name: Call Foundry Model
        env:
          FOUNDRY_ENDPOINT: ${{ secrets.FOUNDRY_ENDPOINT }}
          FOUNDRY_API_KEY: ${{ secrets.FOUNDRY_API_KEY }}
          FOUNDRY_MODEL_DEPLOYMENT: ${{ secrets.FOUNDRY_MODEL_DEPLOYMENT }}
        run: |
          python <<EOF
          import os
          from openai import OpenAI

          client = OpenAI(
              api_key=os.environ["FOUNDRY_API_KEY"],
              base_url=os.environ["FOUNDRY_ENDPOINT"]
          )
      
          response = client.responses.create(
              model=os.environ["FOUNDRY_MODEL_DEPLOYMENT"],
              input="Reply only with: Foundry connection successful"
          )

          print(response.output_text)
          EOF